sudo: false
language: ruby
cache:
  bundler: true
  directories:
  - ".downloads"
  - node_modules
  - tmp/cache/assets/test
  - vendor/assets/bower_components
env:
  global:
  - PATH=$PWD/bin:$PATH
  - secure: DyXBK6bjM0hmuc9caGjpZKpHHzeUdxTwkhGMrrAtUUyVC6i9PH/UL0Keq9rSZs50IwFiC9dCumvUOxNH4SbAMmrJjpw6WHiPG6sZ01x/M/kEbi9QVMe3xu1DPbqpZE0IgeyTXw4D6E6go1SMSrfYenz1qvRV8h7fmJqCjf+UnptWiOfYXeAAFXKvdbbItZs4ABNMtHJ+eP1QKFqQZc5MBNwyA+FZf3HfTipCOQrpTq9W8UG5qaQA5phes6U2s0MdnJJEYQcWr1rMxLA5Z1F+wI9+XtsW6MC0HpJnBQNtLeGDLzHSDv/OivB7/aXXSF9xHh9V0bZWkkpmF1P2EsgWlYPrKRVlgcVnMSLrhPgdUmR7E5Smjyyetdq2I7VmRyw9XbpqJlRWe8N4vUV8SfluzFDSj6M8bXROhnPo6ttYSlCbIMpobd7Z8ZICkv61M4ub3fm8t8feMv7R1bIN3Uh+LXCtM/5yuCiKGOVW0s4XnDOegpBZMk6PSJQq0vD0rYAGvYln2eZs/jZMfZPmRQ28l4RfUQIM1YH85O+14zZ9G4v4fcjafJ9opHxX0cLrHbCfG2528gJKQrvgMiaV/sieqSkromN20AV0A4cTc0onw7Q+sXKjBlY1Jo9SdxnCDc215hCHf0yrwVMy78M2zT6O3W5dqZ6A6QmdrPkbcFx3ihc=
node_js:
- '0.10'
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
before_script:
- "[ -d .downloads ] || mkdir .downloads"
- "(cd .downloads; [ -d prince-9.0r5-linux-amd64-static ] || curl -s http://www.princexml.com/download/prince-9.0r5-linux-amd64-static.tar.gz
  | tar xzf -)"
- echo $PWD | ./.downloads/prince-9.0r5-linux-amd64-static/install.sh
- npm install
- "./bin/rake db:setup RAILS_ENV=test"
notifications:
  slack:
    secure: vN8DJKOIn0EKL98gvHHhGRDEpZsUWXAduypROy5+H1Hvpz9JuNGY87JaExw5o6wO4ejhsDWJ17cWeY7rG31HudWF31EV3LLrMLLr435DcyCQBTfRsTzkFMKH7M+nZj+z4EC64A8QHBOzuz4gwqY0lPsweQPjPAXKeR58kl4inJoUREtVJxBWwh0hzFf3kVQ/8eO11UEPl7bGxmJLFS7MqoXqOYWQzbEg6f4G847/FgzMlGSaSKYRyzLqEgrEwoapq/MG3DDUvINYIsxHCWKY82S3Hs3NV3Lsvcz935hj8SOS9sseCHParORvWES783h2cdpVkpvH6wWlx9u1Zw2GwEcE8A/QKqCv8GJSYORS9Boenau42otchPxGp3gSLAHNxl9iP8Nip6ZrVVYL29uv97z+hiYP7mwqWP4tplzzIRhwRTv1sBeGCI0bCzsOmULxx7hT1BuzgK4UeJTPZfnC7QN2F8FX5KKffS8EmyCmpPhuM0l1sh/QLgwKCJF/XYrpqVgfeH3b6k6v+dW9kxGtr2elCbjEnUJ6rPmcCHwAjclHcg4mqeIfio1zIUV9PU3lIZt+F/1FwK2CTY6DjApp8vKgI+KZIh8u/wB1uUsP/4Ck5ycOEwuwTwbCyuvqnGWmk0qxGsMfA+yS8O0mlzGgAgz2q4LkAbdri4EDwFVJO6Q=
